
![Py4Eng](https://dl.dropboxusercontent.com/u/1578682/py4eng_logo.png)

# Numerical Python: NumPy
## Yoav Ram

# [![Numpy logo](http://www.numpy.org/_static/numpy_logo.png)](http://www.numpy.org/)

[NumPy](http://www.numpy.org/) is the fundamental package for scientific computing with Python. It contains arrays, math functions, linear algebra, random number capabilities and much more.

# "Losing Your Loops": Fast Numerical Computing with NumPy 

From the PyCon 2015 conferece, by [Jake VanderPlas](http://vanderplas.com).

Also available on [YouTube](https://www.youtube.com/watch?v=EEUXKG97YRw).

In [2]:
from IPython.display import HTML
HTML('<script async class="speakerdeck-embed" data-id="a5d2540d0d4c452d91f8045ede6ca130" data-ratio="1.33333333333333" src="//speakerdeck.com/assets/embed.js"></script>')

# Analyzing Patient Data

We are studying inflammation in patients who have been given a new treatment for arthritis, and need to analyze the first dozen data sets. The data sets are stored in comma-separated values (CSV) format: each row holds information for a single patient, and the columns represent successive days. The first few rows of our data file look like this:

> 0,0,1,3,1,2,4,7,8,3,3,3,10,5,7,4,7,7,12,18,6,13,11,11,7,7,4,6,8,8,4,4,5,7,3,4,2,3,0,0
0,1,2,1,2,1,3,2,2,6,10,11,5,9,4,4,7,16,8,6,18,4,12,5,12,7,11,5,11,3,3,5,4,4,5,5,1,1,0,1
0,1,1,3,3,2,6,2,5,9,5,7,4,5,4,15,5,11,9,10,19,14,12,17,7,12,11,7,4,2,10,5,4,2,2,3,2,2,1,1
0,0,2,0,4,2,2,1,6,7,10,7,9,13,8,8,15,10,10,7,17,4,4,7,6,15,6,4,9,11,3,5,6,3,3,4,2,3,2,1
0,1,1,3,3,1,3,5,2,4,4,7,6,5,3,10,8,10,6,17,9,14,9,7,13,9,12,6,7,7,9,6,3,2,2,4,2,0,1,1


## Loading Data
While a lot of powerful tools are built into Python, even more tools exist in the libraries and packages that are written in Python.

In order to load our inflammation data, we need to import a library called __NumPy__.  We could load the data using the __csv__ module, but  you should use NumPy when you want to do things with numbers, especially if you have matrices or tables.

We can load _NumPy_ using import. We also load __urllib__ to read the data from the web:

In [2]:
import numpy as np
print("Numpy version:", np.__version__)
import urllib.request

Numpy version: 1.10.1


First thing, we need to copy the file from the web to our local disk. This is done using the `urllib.request.urlretrieve` function:

In [3]:
url = r"https://raw.githubusercontent.com/swcarpentry/python-novice-inflammation/gh-pages/data/inflammation-01.csv"
fname = r"..\data\inflammation-01.csv"
urllib.request.urlretrieve(url, fname)

('..\\data\\inflammation-01.csv', <http.client.HTTPMessage at 0x5da3f60>)

We saved the file to the local filesystem. 
We can have a look at the file contents from the IPython notebook by calling a system command `cat` or `type`.
To do this, we need to put an `!` at the beginning of the line and prepend any variable name with `$`.

Once it's done, we can ask _Numpy_ to read the data file:

In [9]:
data = np.loadtxt(fname, delimiter=',')
print(data)

[[ 0.  0.  1. ...,  3.  0.  0.]
 [ 0.  1.  2. ...,  1.  0.  1.]
 [ 0.  1.  1. ...,  2.  1.  1.]
 ..., 
 [ 0.  1.  1. ...,  1.  1.  1.]
 [ 0.  0.  0. ...,  0.  2.  0.]
 [ 0.  0.  1. ...,  1.  1.  0.]]


The expression `np.loadtxt(...)` is a function call that asks Python to run the function `loadtxt` that belongs to the `numpy` library. This dotted notation is used everywhere in Python to refer to the parts of things as `thing.component` (see: _namespaces_).

`numpy.loadtxt` has two parameters: the name of the file we want to read, and the delimiter that separates values on a line. These both need to be character strings (or strings for short), so we put them in quotes.

We saved the output of `loadtxt` in the variable `data`. When we `print(data)`, only a few rows and columns are shown (with `...` to omit elements when displaying big arrays). To save space, Python displays numbers as `1.` instead of `1.0` when there's nothing interesting after the decimal point.

## Manipulating Data

Now that our data is in memory, we can start doing things with it. First, let's ask what type of thing data refers to:

In [10]:
print(type(data))

<class 'numpy.ndarray'>


The output tells us that data currently refers to an N-dimensional array created by the NumPy library. We can see what its shape is like this:

In [11]:
print(data.shape)
n_patients,n_days = data.shape

(60, 40)


This tells us that `data` has 60 rows and 40 columns, which are 60 patients and 40 days. `data.shape` is a member of `data`, i.e., a value that is stored as part of a larger value. We use the same dotted notation for the members of values that we use for the functions in libraries because they have the same part-and-whole relationship.

If we want to get a single value from the matrix, we must provide an index in square brackets, just as we do with a `list`, but with as many indices as the number of dimensions in `shape` (two in this case):

In [12]:
print("first value in data",data[0,0])
print("middle value in data:", data[30, 20])

first value in data 0.0
middle value in data: 13.0


The expression `data[30, 20]` may not surprise you, but `data[0, 0]` might. Programming languages like Fortran and MATLAB start counting at 1, because that's what human beings have done for thousands of years. Languages in the C family (including C++, Java, Perl, and Python) count from 0 because that's simpler for computers to do. Just like with `list` and `str`, if we have an M×N array in Python, its indices go from 0 to M-1 on the first axis and 0 to N-1 on the second. It takes a bit of getting used to, but one way to remember the rule is that the index is how many steps we have to take from the start to get the item we want.

> #### In the Corner
> What may also surprise you is that when Python displays an array, it shows the element with index [0, 0] in the upper left corner rather than the lower left. This is consistent with the way mathematicians draw matrices, but different from the Cartesian coordinates. The indices are (row, column) instead of (column, row) for the same reason, which can be confusing when plotting data.

An index like `[30, 20]` selects a single element of an array, but we can select whole sections as well. For example, we can select the first ten days (columns) of values for the first four (rows) patients like this:

In [13]:
print(data[0:4, 0:10])

[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.]
 [ 0.  0.  2.  0.  4.  2.  2.  1.  6.  7.]]


The slice `0:4` means, "Start at index 0 and go up to, but not including, index 4." Again, the up-to-but-not-including takes a bit of getting used to, but the rule is that the difference between the upper and lower bounds is the number of values in the slice.

We don't have to start slices at 0:

In [14]:
print(data[5:10, 0:10])

[[ 0.  0.  1.  2.  2.  4.  2.  1.  6.  4.]
 [ 0.  0.  2.  2.  4.  2.  2.  5.  5.  8.]
 [ 0.  0.  1.  2.  3.  1.  2.  3.  5.  3.]
 [ 0.  0.  0.  3.  1.  5.  6.  5.  5.  8.]
 [ 0.  1.  1.  2.  1.  3.  5.  3.  5.  8.]]


We also don't have to include the upper and lower bound on the slice. If we don't include the lower bound, Python uses 0 by default; if we don't include the upper, the slice runs to the end of the axis, and if we don't include either (i.e., if we just use ':' on its own), the slice includes everything:

In [15]:
small = data[:3, 36:]
print('small is:')
print(small)

small is:
[[ 2.  3.  0.  0.]
 [ 1.  1.  0.  1.]
 [ 2.  2.  1.  1.]]


Arrays also know how to perform common mathematical operations on their values. The simplest operations with data are arithmetic: add, subtract, multiply, and divide. When you do such operations on arrays, the operation is done on each individual element of the array. Thus:

In [16]:
doubledata = data * 2.0

will create a new array `doubledata` whose elements have the value of two times the value of the corresponding elements in `data`.

In [17]:
print('original:')
print(data[:3, 36:])
print('doubledata:')
print(doubledata[:3, 36:])

original:
[[ 2.  3.  0.  0.]
 [ 1.  1.  0.  1.]
 [ 2.  2.  1.  1.]]
doubledata:
[[ 4.  6.  0.  0.]
 [ 2.  2.  0.  2.]
 [ 4.  4.  2.  2.]]


This is also much faster than doing it with vanilla Python:

In [77]:
%timeit [x**2 for x in range(1000)]
%timeit np.arange(1000)**2

1000 loops, best of 3: 571 µs per loop
The slowest run took 5.22 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 5.32 µs per loop


If, instead of taking an array and doing arithmetic with a single value (as above) you did the arithmetic operation with another array of the same size and shape, the operation will be done on corresponding elements of the two arrays. Thus:

In [18]:
tripledata = doubledata + data

will give you an array where `tripledata[0,0]` will equal `doubledata[0,0]` plus `data[0,0]`, and so on for all other elements of the arrays.

In [19]:
print('tripledata:')
print(tripledata[:3, 36:])

tripledata:
[[ 6.  9.  0.  0.]
 [ 3.  3.  0.  3.]
 [ 6.  6.  3.  3.]]


Just another `timeit` comparison:

In [78]:
%timeit [x + y**0.5 for x, y in zip(range(1000), range(1000))]
%timeit np.arange(1000) + np.arange(1000)**0.5

1000 loops, best of 3: 531 µs per loop
10000 loops, best of 3: 72 µs per loop


## Exercise

Calculate the square root of the data using `numpy`. 
Print the result for the first 5 columns of the first 3 rows.

## Getting help

You can try:

In [79]:
np.arange?

In [80]:
np.lookfor('zeros')

Search results for 'zeros'
--------------------------
numpy.zeros
    Return a new array of given shape and type, filled with zeros.
numpy.eye
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
numpy.tri
    An array with ones at and below the given diagonal and zeros elsewhere.
numpy.trim_zeros
    Trim the leading and/or trailing zeros from a 1-D array or sequence.
numpy.zeros_like
    Return an array of zeros with the same shape and type as a given array.
numpy.ma.zeros
    Return a new array of given shape and type, filled with zeros.
numpy.matlib.zeros
    Return a matrix of given shape and type, filled with zeros.
numpy.matlib.eye
    Return a matrix with ones on the diagonal and zeros elsewhere.
numpy.bytes0.zfill
    B.zfill(width) -> copy of B
numpy.str0.zfill
    S.zfill(width) -> str
numpy.chararray.zfill
    Return the numeric string left-filled with zeros in a string of
numpy.polynomial.Hermite._roots
    Compute the roots of a Hermite series.
numpy.poly

In [81]:
np.concat*?

## Descriptive statistics

Often, we want to do more than add, subtract, multiply, and divide values of data. Arrays also know how to do more complex operations on their values. If we want to find the average inflammation for all patients on all days, for example, we can just ask the array for its mean value

In [20]:
print(data.mean())

6.14875


`mean` is a method of the array, i.e., a function that belongs to it in the same way that the member shape does. If variables are nouns, methods are verbs: they are what the thing in question knows how to do. This is why `data.shape` doesn't need to be called (it's just a thing) but `data.mean()` does (it's an action). It is also why we need empty parentheses for `ata.mean()`: even when we're not passing in any parameters, parentheses are how we tell Python to go and do something for us.

NumPy arrays have lots of useful methods:

In [21]:
print('maximum inflammation:', data.max())
print('minimum inflammation:', data.min())
print('standard deviation:', data.std())

maximum inflammation: 20.0
minimum inflammation: 0.0
standard deviation: 4.61383319712


When analyzing data, though, we often want to look at partial statistics, such as the maximum value per patient or the average value per day. One way to do this is to select the data we want to create a new temporary array, then ask it to do the calculation:

In [22]:
patient_0 = data[0, :] # 0 on the first axis, everything on the second
print('maximum inflammation for patient 0:', patient_0.max())

maximum inflammation for patient 0: 18.0


What if we need the maximum inflammation for all patients, or the average for each day? As the diagram below shows, we want to perform the operation across an axis:
![axis example](http://software-carpentry.org/v5/novice/python/img/python-operations-across-axes.svg)
To support this, most array methods allow us to specify the axis we want to work on. If we ask for the average across axis 0, we get:

In [23]:
print(data.mean(axis=0))

[  0.           0.45         1.11666667   1.75         2.43333333   3.15
   3.8          3.88333333   5.23333333   5.51666667   5.95         5.9
   8.35         7.73333333   8.36666667   9.5          9.58333333
  10.63333333  11.56666667  12.35        13.25        11.96666667
  11.03333333  10.16666667  10.           8.66666667   9.15         7.25
   7.33333333   6.58333333   6.06666667   5.95         5.11666667   3.6
   3.3          3.56666667   2.48333333   1.5          1.13333333
   0.56666667]


As a quick check, we can ask this array what its shape is:

In [24]:
print(data.mean(axis=0).shape)

(40,)


The expression `(40,)` tells us we have an N×1 vector, so this is the average inflammation per day for all patients. If we average across axis 1, we get:

In [25]:
print(data.mean(axis=1))

[ 5.45   5.425  6.1    5.9    5.55   6.225  5.975  6.65   6.625  6.525
  6.775  5.8    6.225  5.75   5.225  6.3    6.55   5.7    5.85   6.55
  5.775  5.825  6.175  6.1    5.8    6.425  6.05   6.025  6.175  6.55
  6.175  6.35   6.725  6.125  7.075  5.725  5.925  6.15   6.075  5.75
  5.975  5.725  6.3    5.9    6.75   5.925  7.225  6.15   5.95   6.275  5.7
  6.1    6.825  5.975  6.725  5.7    6.25   6.4    7.05   5.9  ]


which is the average inflammation per patient across all days.

## Exercise

On which day did each patient had the most inflammation?
Use `data.argmax` to find out.

## Creating arrays

There are many ways to create arrays:

In [84]:
a = np.array([0, 1, 2, 3])
print(a)

[0 1 2 3]


In [85]:
b = np.array(
    [
        [0, 1, 2], 
        [3, 4, 5]
    ]
)
print(b)

[[0 1 2]
 [3 4 5]]


In [86]:
c = np.array(
    [
        [
            [1], 
            [2]
        ], 
        [
            [3], 
            [4]
        ]
    ]
)
print(c)

[[[1]
  [2]]

 [[3]
  [4]]]


In [90]:
a = np.arange(10)  # end (exclusive)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [91]:
b = np.arange(1, 9, 2) # start, end (exclusive), step
print(b)

[1 3 5 7]


In [92]:
c = np.linspace(0, 1, 6)   # start, end, num-points
print(c)

[ 0.   0.2  0.4  0.6  0.8  1. ]


In [107]:
d = np.empty((2, 4))
print(d)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [108]:
f = np.empty_like(a)
print(f)

[ 0.  0.  0.  0.]


In [93]:
a = np.ones((3, 3))  # reminder: (3, 3) is a tuple
print(a)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [94]:
b = np.zeros((2, 2))
print(b)

[[ 0.  0.]
 [ 0.  0.]]


In [95]:
c = np.eye(3)
print(c)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [115]:
d = np.diag(np.array([1, 2, 3, 4]))
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [116]:
f = d.reshape((2, 8))
print(f)

[[1 0 0 0 0 2 0 0]
 [0 0 3 0 0 0 0 4]]


In [117]:
np.random.seed(0)           # Setting the random seed for reproducability
a = np.random.random(size=4) # uniform in [0, 1]
print(a)

[ 0.5488135   0.71518937  0.60276338  0.54488318]


In [118]:
b = np.random.normal(0, 1, size=(2, 2)) # standard normal
print(b)

[[ 1.86755799 -0.97727788]
 [ 0.95008842 -0.15135721]]


In [119]:
c = np.random.poisson(5, size=(3, 2, 4)) # standard normal
print(c)

[[[ 6  1  9  7]
  [ 8  4  5  4]]

 [[ 3  3  7  3]
  [ 3  4  5  2]]

 [[ 1  7  7 10]
  [ 5  8  8  6]]]


## Exercise

Skim through the documentation for `np.tile`, and use this function to construct the array:
```py
[
    [4, 3, 4, 3, 4, 3], 
    [2, 1, 2, 1, 2, 1], 
    [4, 3, 4, 3, 4, 3], 
    [2, 1, 2, 1, 2, 1]
] 
```

## Colophon
This notebook was written by [Yoav Ram](http://www.yoavram.com) and is part of the _Python for Engineers_ course.

The notebook was written using [Python](http://pytho.org/) 3.4.4, [IPython](http://ipython.org/) 4.0.3 and [Jupyter](http://jupyter.org) 4.0.6.

This work is licensed under a CC BY-NC-SA 4.0 International License.

![Python logo](https://www.python.org/static/community_logos/python-logo.png)